INSERT INTO PROPIETARIO(CEDULA,NOMBRE) VALUES('1140844836','ARMANDO PALMERA');

INSERT INTO PAIS(CODIGO,IDIOMA,MONEDA) VALUES ('CO','SPANISH','COP');

INSERT INTO ESTRATO(CLASIFICACION,DIRECCION)  VALUES('1','BUENOS AIRES');
INSERT INTO ESTRATO(CLASIFICACION,DIRECCION)  VALUES('3','ENVIGADO');
INSERT INTO ESTRATO(CLASIFICACION,DIRECCION)  VALUES('2','BELLO');


